# Generated by Django 6.0.7 on 2026-07-31 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('identifier', models.CharField(blank=True, max_length=100)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('successful', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('special_number', models.CharField(max_length=20, unique=True, verbose_name='الرقم المميز')),
                ('student_phone', models.CharField(max_length=20, verbose_name='هاتف الطالب')),
                ('parent_phone', models.CharField(max_length=20, verbose_name='هاتف الأهل')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('grade_level', models.CharField(choices=[('first', 'الأول'), ('second', 'الثاني'), ('third', 'الثالث'), ('fourth', 'الرابع')], max_length=20, verbose_name='المرحلة')),
                ('section', models.CharField(choices=[('a', 'أ'), ('b', 'ب'), ('c', 'ج')], max_length=5, verbose_name='الشعبة')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('special_number', models.CharField(max_length=20, unique=True, verbose_name='الرقم المميز')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('phone', models.CharField(max_length=20, verbose_name='الهاتف')),
                ('subject', models.CharField(max_length=100, verbose_name='المادة')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='السيرة الذاتية')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'أستاذ',
                'verbose_name_plural': 'الأساتذة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_number', models.CharField(max_length=20, unique=True, verbose_name='الرقم المميز')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مدير',
                'verbose_name_plural': 'المدراء',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('full', 'دفعة كاملة'), ('installment', 'تقسيط')], max_length=15, verbose_name='نوع الدفعة')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الكلي')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المدفوع')),
                ('status', models.CharField(choices=[('pending', 'قيد التحصيل'), ('completed', 'مكتمل')], default='pending', max_length=15, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'المدفوعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=150, verbose_name='اسم المذاكرة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('section', models.CharField(choices=[('a', 'أ'), ('b', 'ب'), ('c', 'ج')], max_length=5, verbose_name='الشعبة')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='العلامة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'علامة',
                'verbose_name_plural': 'العلامات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sunday', 'الأحد'), ('monday', 'الاثنين'), ('tuesday', 'الثلاثاء'), ('wednesday', 'الأربعاء'), ('thursday', 'الخميس'), ('friday', 'الجمعة'), ('saturday', 'السبت')], max_length=15, verbose_name='اليوم')),
                ('grade_level', models.CharField(choices=[('first', 'الأول'), ('second', 'الثاني'), ('third', 'الثالث'), ('fourth', 'الرابع')], max_length=20, verbose_name='المرحلة')),
                ('section', models.CharField(choices=[('a', 'أ'), ('b', 'ب'), ('c', 'ج')], max_length=5, verbose_name='الشعبة')),
                ('subject', models.CharField(max_length=100, verbose_name='المادة')),
                ('room', models.CharField(max_length=50, verbose_name='القاعة')),
                ('time', models.TimeField(verbose_name='الساعة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.teacher', verbose_name='الأستاذ')),
            ],
            options={
                'verbose_name': 'حصة',
                'verbose_name_plural': 'البرنامج الدراسي',
                'ordering': ['day', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('section', models.CharField(choices=[('a', 'أ'), ('b', 'ب'), ('c', 'ج')], max_length=5, verbose_name='الشعبة')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب')], max_length=10, verbose_name='الحالة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'حضور',
                'verbose_name_plural': 'الحضور والغياب',
                'ordering': ['-date'],
                'unique_together': {('date', 'student')},
            },
        ),
    ]
